### ISSUE TITLE
No Files while trying to run the pack under DOSBox

### ISSUE THREAD

**Issue by meowthed** [flynnsbit/DOS_Shareware_MyMenu#1]
![Untitled](https://user-images.githubusercontent.com/41223243/144846331-17778fe0-fce1-4acd-96d1-14b433b52616.png)

ran AUTOEXEC.BAT, still showing the same message.

**Comment by flynnsbit** [comment]
DOSBox has something up with its implementation of Long File Name support that makes it different than all others (86Box/PCem).  You can set LFN=F in mymenu.ini and the files will show (except it will be the 8.3 version of the file)

**Comment by meowthed** [comment]
It now works when LFN is set to F, but now the filenames are cut to DOS standards. Better than to show nothing for now.

**Comment by bbond007** [comment]
Dosbox does not have (full) LFN support.

Does does not seem to properly support Intr 0x21 0x714E, 0x714F

Example code: http://swag.outpostbbs.net/FILES/0086.PAS.html
